/* Main.c file generated by New Project wizard
 *
 * Created:   Sat Feb 19 2022
 * Processor: LPC1114FBD48/301
 * Compiler:  GCC for ARM
 */

#include <LPC11xx.h>


#define GPIO0DIR (*((volatile unsigned long *)0x50008000))
#define GPIO0DATA (*((volatile unsigned long *)0x50003FFC))

void main () { 
    GPIO0DIR |= 0b100;
      while (1){
	 if( GPIO0DATA &  0b10){
	    GPIO0DATA ^= 0b100;

	    while( GPIO0DATA  &  0b10);
	 }
      }
 }   

