/* Main.c file generated by New Project wizard
 *
 * Created:   Fri Mar 4 2022
 * Processor: LPC1114FBD48/301
 * Compiler:  GCC for ARM
 */


#include "displaylib.h"


#define GPIO3DIR (*((volatile unsigned long *)0x50038000))
#define GPIO3DATA (*((volatile unsigned long *)0x50030018))


#define GPIO2DIR (*((volatile unsigned long *)0x50028000))
#define GPIO2DATA (*((volatile unsigned long *)0x5002003C))


int main (void)
{ 
   // Write your code here
    GPIO3DIR |= 0xFF;
    GPIO2DIR |= 0b101;
   
   setup();
   send_str("120181499");

    while (1);
    return 0;
}   
